# Generated by Django 3.1.7 on 2022-09-17 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0002_auto_20220917_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='owner_firstname',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner_lastname',
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
