# Generated by Django 3.1.7 on 2022-09-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20220917_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner_fist_name',
            field=models.CharField(default='test_first', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='owner_last_name',
            field=models.CharField(default='test_last', max_length=40),
            preserve_default=False,
        ),
    ]
