# Generated by Django 3.1.7 on 2022-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20220917_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessibilitycategory',
            name='name',
            field=models.CharField(choices=[('PARKING', 'Parking'), ('RAMP', 'Ramp'), ('ELEVATORS', 'Elevators')], default='PARKING', max_length=40),
        ),
    ]
