# Generated by Django 3.1.7 on 2022-09-17 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_accessibilitycategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilitycategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_categories', to='stores.store'),
        ),
    ]
