# Generated by Django 3.1.7 on 2022-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20220917_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_category',
            field=models.CharField(choices=[('RESTAURANT', 'Restaurant'), ('GROCERY STORE', 'Grocery Store')], default='RESTAURANT', max_length=40),
        ),
    ]
