# Generated by Django 3.1.7 on 2022-09-17 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20220917_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilitycategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
