# Generated by Django 3.1.7 on 2022-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
