# Generated by Django 3.1.7 on 2022-09-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_auto_20220917_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
