# Generated by Django 3.1.7 on 2022-09-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_store_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
